project:
  type: website
  resources:
    - "*.pdf"
    - publications/
    - CNAME
    - robots.txt
    - documents/
    - images/

website:
  title: "Eiren Kate Jacobson, Ph.D."
  favicon: images/favicons/favicon.ico
  navbar:
    right:
      - href: index.qmd
        text: About
      - href: publications.qmd
        text: Publications
      - href: Jacobson_Resume_Oct2026.pdf
        text: CV
  page-footer: "© 2026 Eiren Jacobson"

format:
  html:
    theme: [flatly, custom.scss]
    toc: false
